# Syntax files are pretty much impossible to test, so just exclude them.
# https://docs.codecov.io/docs/ignoring-paths
ignore: ["syntax/*"]
comment: off
coverage:
  range: 50..90
  round: down
  precision: 2
  status:
    patch: false
