language: go
go:
  - 1.11.x
  - 1.12.x
notifications:
  email: false
cache:
  directories:
    - "$HOME/vim"

install: |
  # Use Python 3
  pyenv global 3.7

  # Move plugin to more logical location.
  cd ~
  mkdir -p ~/.vim/pack/plugin/start
  mv /home/travis/gopath/src/github.com/arp242/gopher.vim ~/.vim/pack/plugin/start

  (
    set -euC

    # Install Vim if there it doesn't exist yet.
    if [ ! -e "$HOME/vim/bin/vim" ]; then
      git clone -q --depth 1 --branch "v8.0.0400" https://github.com/vim/vim $HOME/vim-src
      ( cd $HOME/vim-src && ./configure --prefix $HOME/vim --with-features=huge --disable-gui )
      ( cd $HOME/vim-src && make install )
    fi

    # testing.vim
    pip3 install --user -q vim-vint covimerage codecov
    git clone -q --depth 1 https://github.com/arp242/testing.vim.git $HOME/testing.vim

    # Lint tools
    # pack="$HOME/vim/share/vim/vim80/pack/dist/start"
    # mkdir -p "$pack"
    # [ -d "$pack/vim-vimhelplint" ] || git clone -q --depth 1 https://github.com/machakann/vim-vimhelplint "$pack/vim-vimhelplint"
    # [ -d "$pack/vim-vimlparser" ]  || git clone -q --depth 1 https://github.com/ynkdir/vim-vimlparser     "$pack/vim-vimlparser"
    # [ -d "$pack/vim-vimlint" ]     || git clone -q --depth 1 https://github.com/syngan/vim-vimlint        "$pack/vim-vimlint"
  )

script: |
  (
    set -euC
    cd ~/.vim/pack/plugin/start/gopher.vim
    PATH="$HOME/vim/bin:$PATH" $HOME/testing.vim/tvim test -p coverage.xml ./...
    PATH="$HOME/vim/bin:$PATH" $HOME/testing.vim/tvim lint ./...
  )

after_success: |
  (
    cd ~/.vim/pack/plugin/start/gopher.vim
    codecov -X search gcov pycov -f coverage.xml --required
  )
